spring:
  application:
    name: collector
  kafka:
    bootstrap-servers: localhost:9092

collector:
  kafka:
    topics:
      sensors: telemetry.sensors.v1
      hubs: telemetry.hubs.v1

server:
  port: 8080

logging:
  level:
    ru.yandex.practicum: DEBUG