spring:
  application:
    name: shopping-store
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    config:
      fail-fast: false
      retry:
        useRandomPolicy: true
        max-interval: 30000
        initial-interval: 5000
        multiplier: 2.0
        max-attempts: 10
  datasource:
    url: jdbc:postgresql://localhost:5433/shopping_store
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 0

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/